#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
TOTAL_MINUTES=55
ENV_FILE="${ENV_FILE:-.env.deno-deploy-migration}"

scan_code() {
  local pattern="$1"
  if command -v rg >/dev/null 2>&1; then
    rg -n "$pattern" . --glob '!*.lock' --glob '!.git' || true
  else
    grep -RInE "$pattern" . --exclude-dir=.git --exclude='*.lock' || true
  fi
}

prompt_env_vars() {
  say "Enter each Deploy Classic environment variable exactly once."
  note "For secrets, choose hidden entry. Press Enter on an empty key when done."
  while true; do
    ask MIGRATION_ENV_KEY "Env var key (blank when done):"
    [[ -z "${MIGRATION_ENV_KEY:-}" ]] && break
    if confirm "Is $MIGRATION_ENV_KEY secret?"; then
      ask_secret MIGRATION_ENV_VALUE "Paste $MIGRATION_ENV_KEY value:"
    else
      ask MIGRATION_ENV_VALUE "Paste $MIGRATION_ENV_KEY value:"
    fi
    write_env "$MIGRATION_ENV_KEY" "$MIGRATION_ENV_VALUE"
    pause "Recreate $MIGRATION_ENV_KEY in the new Deploy dashboard, then press Enter."
  done
}

show_kv_migration_scripts() {
  say "Use one-time Deno scripts so the migration is reviewable, repeatable, and app-specific."
  note "Reference: https://docs.deno.com/deploy/reference/deno_kv/"
  note "New Deploy apps use Deno.openKv() after a KV database is assigned. Local scripts use the URL connector."
  warn "These examples copy keys and values. If your app relies on key expiration, reapply TTLs in app-specific code."
  printf '\n'
  step "Preview or export from the source KV. Pipe this into deno eval, or save it as kv-export-once.ts."
  cat <<'EOF'

const kvUrl = Deno.env.get("KV_URL");
const outPath = Deno.env.get("KV_OUT") ?? "kv-export.jsonl";
const prefix = JSON.parse(Deno.env.get("KV_PREFIX") ?? "[]");
const limit = Number(Deno.env.get("KV_LIMIT") ?? "0");
const preview = Deno.args.includes("--preview");

if (!kvUrl) {
  throw new Error("Set KV_URL to a Deno KV connect URL");
}

function encode(value: unknown): unknown {
  if (value instanceof Uint8Array) {
    return { __kvType: "Uint8Array", data: btoa(String.fromCharCode(...value)) };
  }
  if (value instanceof Deno.KvU64) {
    return { __kvType: "KvU64", data: value.value.toString() };
  }
  if (typeof value === "bigint") {
    return { __kvType: "bigint", data: value.toString() };
  }
  if (value instanceof Date) {
    return { __kvType: "Date", data: value.toISOString() };
  }
  if (value instanceof RegExp) {
    return { __kvType: "RegExp", source: value.source, flags: value.flags };
  }
  if (value instanceof Map) {
    return { __kvType: "Map", data: [...value.entries()].map(([k, v]) => [encode(k), encode(v)]) };
  }
  if (value instanceof Set) {
    return { __kvType: "Set", data: [...value.values()].map(encode) };
  }
  if (Array.isArray(value)) return value.map(encode);
  if (value !== null && typeof value === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) result[key] = encode(item);
    return result;
  }
  return value;
}

const kv = await Deno.openKv(kvUrl);
const out = preview ? undefined : await Deno.open(outPath, {
  create: true,
  write: true,
  truncate: true,
});
const encoder = new TextEncoder();
let count = 0;

try {
  for await (const entry of kv.list({ prefix }, { batchSize: 500 })) {
    const record = {
      key: encode(entry.key),
      value: encode(entry.value),
      versionstamp: entry.versionstamp,
    };
    const line = JSON.stringify(record);
    if (preview) console.log(line);
    else await out!.write(encoder.encode(line + "\n"));

    count++;
    if (limit > 0 && count >= limit) break;
  }
} finally {
  out?.close();
  kv.close();
}

console.error(JSON.stringify({ mode: preview ? "preview" : "export", prefix, count, outPath }));
EOF

  printf '\n'
  step "Dry-run or import into the target KV. Pipe this into deno eval, or save it as kv-import-once.ts."
  cat <<'EOF'

const kvUrl = Deno.env.get("KV_URL");
const inPath = Deno.env.get("KV_IN") ?? "kv-export.jsonl";
const dryRun = Deno.args.includes("--dry-run");
const overwrite = Deno.args.includes("--overwrite");

if (!kvUrl) {
  throw new Error("Set KV_URL to https://api.deno.com/v2/databases/<Database ID>/connect");
}
if (overwrite && !Deno.args.includes("--i-understand-overwrite")) {
  throw new Error("Overwrite is destructive. Re-run with --overwrite --i-understand-overwrite if intentional.");
}

type EncodedValue = {
  __kvType?: string;
  data?: unknown;
  source?: string;
  flags?: string;
};

function decode(value: unknown): unknown {
  if (value && typeof value === "object" && "__kvType" in value) {
    const encoded = value as EncodedValue;
    switch (encoded.__kvType) {
      case "Uint8Array":
        return Uint8Array.from(atob(encoded.data as string), (char) => char.charCodeAt(0));
      case "KvU64":
        return new Deno.KvU64(BigInt(encoded.data as string));
      case "bigint":
        return BigInt(encoded.data as string);
      case "Date":
        return new Date(encoded.data as string);
      case "RegExp":
        return new RegExp(encoded.source ?? "", encoded.flags ?? "");
      case "Map":
        return new Map((encoded.data as [unknown, unknown][]).map(([key, item]) => [decode(key), decode(item)]));
      case "Set":
        return new Set((encoded.data as unknown[]).map(decode));
    }
  }
  if (Array.isArray(value)) return value.map(decode);
  if (value !== null && typeof value === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) result[key] = decode(item);
    return result;
  }
  return value;
}

const kv = await Deno.openKv(kvUrl);
const file = await Deno.open(inPath, { read: true });
let processed = 0;
let imported = 0;
let skipped = 0;

async function importLine(line: string) {
  if (!line.trim()) return;
  const entry = JSON.parse(line) as { key: unknown; value: unknown };
  const key = decode(entry.key) as Deno.KvKey;
  const value = decode(entry.value);
  processed++;

  if (dryRun) {
    const existing = await kv.get(key);
    if (existing.versionstamp === null || overwrite) imported++;
    else skipped++;
    return;
  }

  const result = overwrite
    ? await kv.atomic().set(key, value).commit()
    : await kv.atomic().check({ key, versionstamp: null }).set(key, value).commit();

  if (result.ok) imported++;
  else skipped++;
}

try {
  let pending = "";
  for await (const chunk of file.readable.pipeThrough(new TextDecoderStream())) {
    const lines = (pending + chunk).split("\n");
    pending = lines.pop() ?? "";

    for (const line of lines) {
      await importLine(line);
    }
  }

  await importLine(pending);
} finally {
  file.close();
  kv.close();
}

console.log(JSON.stringify({ dryRun, overwrite, processed, imported, skipped, inPath }));
EOF

  printf '\n'
  step "Example commands:"
  cat <<'EOF'

# New Deploy target URL format from the Deno KV reference:
# https://api.deno.com/v2/databases/<Database ID>/connect

# Preview a prefix from the source KV after saving kv-export-once.ts:
DENO_KV_ACCESS_TOKEN="<source-token>" \
KV_URL="<source-kv-connect-url>" \
KV_PREFIX='["replace-with-app-prefix"]' \
deno run --unstable-kv --allow-env --allow-net kv-export-once.ts --preview

# Export that prefix to JSONL:
DENO_KV_ACCESS_TOKEN="<source-token>" \
KV_URL="<source-kv-connect-url>" \
KV_PREFIX='["replace-with-app-prefix"]' \
KV_OUT="kv-export.jsonl" \
deno run --unstable-kv --allow-env --allow-net --allow-write kv-export-once.ts

# Dry-run import into the new Deploy KV:
DENO_KV_ACCESS_TOKEN="<new-deploy-token>" \
KV_URL="https://api.deno.com/v2/databases/<Database ID>/connect" \
KV_IN="kv-export.jsonl" \
deno run --unstable-kv --allow-env --allow-net --allow-read kv-import-once.ts --dry-run

# Real import. Default behavior skips keys that already exist in the target:
DENO_KV_ACCESS_TOKEN="<new-deploy-token>" \
KV_URL="https://api.deno.com/v2/databases/<Database ID>/connect" \
KV_IN="kv-export.jsonl" \
deno run --unstable-kv --allow-env --allow-net --allow-read kv-import-once.ts

# deno eval form after saving either script. deno eval has implicit permissions:
deno eval --unstable-kv --ext=ts "$(cat kv-export-once.ts)" -- --preview
EOF
}

banner "Deno Deploy Classic migration"

stage "Identify the project" 5
say "Run this wizard from the root of one Deploy Classic project. Re-run it for each project."
open_url "https://dash.deno.com/projects"
step "Open the Deploy Classic project you are migrating."
ask DENO_CLASSIC_PROJECT_NAME "Classic project name:"
ask DENO_CLASSIC_PROJECT_URL "Classic project URL (optional, press Enter to skip):"
write_env DENO_CLASSIC_PROJECT_NAME "$DENO_CLASSIC_PROJECT_NAME"
[[ -n "${DENO_CLASSIC_PROJECT_URL:-}" ]] && write_env DENO_CLASSIC_PROJECT_URL "$DENO_CLASSIC_PROJECT_URL"

stage "Read the migration guide" 3
open_url "https://docs.deno.com/deploy/migration_guide/"
say "Deno Deploy Classic and subhosting v1 shut down on July 20, 2026."
step "Keep the migration guide open while you work through this project."
pause "Press Enter when the guide is open."

stage "Create the new organization and app shell" 7
open_url "https://console.deno.com"
step "Sign in to the new Deno Deploy console."
step "Create an organization if you do not already have one."
step "Create a new app for this classic project."
ask DENO_ORG_NAME "New Deno organization name:"
ask DENO_APP_NAME "New Deno app name:"
ask DENO_APP_ID "New Deno app/project ID (if visible, optional):"
write_env DENO_ORG_NAME "$DENO_ORG_NAME"
write_env DENO_APP_NAME "$DENO_APP_NAME"
[[ -n "${DENO_APP_ID:-}" ]] && write_env DENO_APP_ID "$DENO_APP_ID"

stage "Audit HTTP server API" 6
say "The new Deploy does not support legacy std/http serve(). It must use Deno.serve()."
step "Review these possible legacy server API references:"
scan_code 'std(@[0-9.]+)?/http/server\.ts|from ["'\'' ]?@std/http/server|serve\('
warn "If any match is the old imported serve() API, update it before deploying."
note "Typical migration: remove the std/http server import and call Deno.serve(handler)."
pause "Press Enter after reviewing or fixing HTTP server API usage."

stage "Audit queues and KV" 5
say "Deno.cron() works on new Deploy. Deno queues do not. KV exists, but data is not auto-migrated."
step "Review queue usage:"
scan_code 'Deno\.Kv\.(enqueue|listenQueue)|\.enqueue\(|listenQueue\('
warn "If this project uses queues, replace them with an external queue or database-backed jobs before cutover."
step "Review KV usage:"
scan_code 'Deno\.openKv|Deno\.Kv|openKv\('
if confirm "Does this project need KV data migrated?"; then
  open_url "https://docs.deno.com/deploy/reference/deno_kv/"
  warn "Do not delete or unassign source KV data until export, import, and verification all pass."
  step "In the new Deploy console, provision a Deno KV database and assign it to the app."
  step "Confirm the target timeline/database. New Deploy isolates databases per timeline."
  step "Inspect this app's source code and choose the exact KV key prefixes to migrate."
  ask DENO_CLASSIC_KV_CONNECT_URL "Source KV connect URL:"
  ask DENO_NEW_KV_CONNECT_URL "New Deploy KV connect URL (https://api.deno.com/v2/databases/<Database ID>/connect):"
  ask DENO_KV_EXPORT_FILE "KV export file path [kv-export.jsonl]:"
  DENO_KV_EXPORT_FILE="${DENO_KV_EXPORT_FILE:-kv-export.jsonl}"
  write_env DENO_CLASSIC_KV_CONNECT_URL "$DENO_CLASSIC_KV_CONNECT_URL"
  write_env DENO_NEW_KV_CONNECT_URL "$DENO_NEW_KV_CONNECT_URL"
  write_env DENO_KV_EXPORT_FILE "$DENO_KV_EXPORT_FILE"
  show_kv_migration_scripts
  step "Run preview/export with the source token, then dry-run/import with the new Deploy token."
  step "Verify counts and representative keys in the new app before cutover."
  if ! confirm "Did KV export, dry-run import, real import, and verification all pass?"; then
    SKIPPED+=("Finish self-serve KV export/import/verification for $DENO_CLASSIC_PROJECT_NAME")
    SKIPPED+=("Use support@deno.com as the KV migration escape hatch if remote access or verification fails")
    open_url "mailto:support@deno.com?subject=Deno%20KV%20migration%20request%20for%20$DENO_CLASSIC_PROJECT_NAME"
  fi
fi

stage "Migrate environment variables" 10
open_url "https://dash.deno.com/projects"
step "In Deploy Classic, open this project, then open Settings -> Environment Variables."
open_url "https://console.deno.com"
step "In the new app, open Settings -> Environment Variables."
say "Deploy Classic had one env var set. New Deploy separates production, development, and build contexts."
prompt_env_vars

stage "Deploy the app" 8
say "Use either the new dashboard GitHub integration or the Deno CLI. deployctl is being sunset."
if confirm "Use the GitHub dashboard integration?"; then
  open_url "https://console.deno.com"
  step "Open the new app settings."
  step "Connect the GitHub repository and configure the branch/build settings."
  pause "Press Enter after the first deployment starts or succeeds."
else
  step "Install or upgrade Deno if needed, then run this from the project root: deno deploy"
  pause "Press Enter after you run deno deploy and it succeeds."
fi
ask DENO_APP_URL "New app URL:"
write_env DENO_APP_URL "$DENO_APP_URL"

stage "Migrate custom domains" 7
if confirm "Does this project use a custom domain?"; then
  open_url "https://docs.deno.com/examples/migrate_custom_domain_tutorial/"
  open_url "https://console.deno.com"
  ask DENO_CUSTOM_DOMAIN "Custom domain:"
  write_env DENO_CUSTOM_DOMAIN "$DENO_CUSTOM_DOMAIN"
  step "In the new app, add the custom domain."
  step "Create the _acme-challenge CNAME shown by the dashboard for TLS provisioning."
  step "Update your DNS CNAME or ANAME record to point at the new Deploy target."
  warn "Allow up to 48 hours for DNS propagation before removing the domain from Deploy Classic."
  pause "Press Enter after the new domain is added and DNS changes are queued."
else
  note "Skipping custom domain migration."
fi

stage "Smoke test the new app" 5
say "Confirm the new app works before touching the classic deployment."
[[ -n "${DENO_APP_URL:-}" ]] && open_url "$DENO_APP_URL"
step "Test the homepage and one important route or workflow."
step "Check logs, traces, and metrics in the new Deploy dashboard."
if ! confirm "Did the new app pass smoke testing?"; then
  SKIPPED+=("Fix migration issues before decommissioning $DENO_CLASSIC_PROJECT_NAME")
  warn "Do not decommission Deploy Classic yet."
fi

stage "Decommission Deploy Classic" 4
warn "This is the irreversible cutover step. Only continue after traffic, env vars, domains, and data are verified."
if confirm "Is it safe to remove or disable the classic project now?"; then
  open_url "https://dash.deno.com/projects"
  step "Open the classic project."
  step "Remove the custom domain only after DNS has propagated to the new app."
  step "Delete or disable the classic deployment/project."
  pause "Press Enter after the classic project is decommissioned."
else
  SKIPPED+=("Decommission Deploy Classic project $DENO_CLASSIC_PROJECT_NAME after final verification")
fi

finish
